pipeline:
  # Step 1: Generate changelog for later use
  changelog:
    image: lawnchairlauncher/drone-changelog:latest
    output: changelog.txt
    volumes:
      - /opt/drone/cache:/cache
    when:
      event: push

  # Step 2: The actual point of all of this
  build:
    image: runmymind/docker-android-sdk:ubuntu-standalone
    secrets: [ store_password, key_password, github_token, encryption_key ]
    environment:
      - MAJOR_MINOR=0.1.0
      - TRAVIS=true
      - TRAVIS_BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - TRAVIS_EVENT_TYPE=${DRONE_BUILD_EVENT}
    commands:
      - bash ./gradlew app:assembleOptimized

  # Step 3: Create coverage report on Codacy
  codacy:
    image: plugins/codacy
    secrets: [ codacy_token ]

  # Step 4: Upload to Telegram or Transfer.sh, depending on the event
  deploy:
    image: lawnchairlauncher/drone-telegram:latest
    secrets: [ bot_token, channel_id, dev_channel_id ]
    apk_path: app/build/outputs/apk/optimized/app-optimized.apk
    mapping_path: app/build/outputs/mapping/optimized/mapping.txt
    filename: "mKKM-Webview"
    channel_id: "-1001351740621"
    environment:
      - MAJOR_MINOR=${DRONE_BRANCH}
    when:
      event: push
      status: success

branches:
  exclude: [ l10n_alpha2, v1-alpha ]
